import { TABLE_COLUMN_NAMES } from './TableColumnNames';

export const ACTION_TYPE = {
    VIEW: TABLE_COLUMN_NAMES.VIEW,
    MODIFY: TABLE_COLUMN_NAMES.MODIFY,
    DELETE: TABLE_COLUMN_NAMES.DELETE,
    MODIFY_STATUS: `${TABLE_COLUMN_NAMES.MODIFY} ${TABLE_COLUMN_NAMES.STATUS}`,
};
